# Generated by Django 3.1.4 on 2020-12-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fameza', '0005_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pedido Confirmado', 'Pedido Confirmado'), ('En proceso de entrega', 'En proceso de entrega'), ('Entregado', 'Entregado')], max_length=50, null=True),
        ),
    ]
