# Generated by Django 3.1.4 on 2020-12-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fameza', '0009_auto_20201211_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
